# Einweg ANOVA {#sec-simple-anova}

## Die Daten

```{r setup, include=FALSE}
## Warning: to compile the notes you need the "bookdown" and the "broom" packages. Install them by
## running install.packages, see the commented lines below

if (!require("tidyverse")) {
  install.packages("tidyverse", repos = "http://cran.us.r-project.org")
}

if (!require("broom")) {
  install.packages("broom", repos = "http://cran.us.r-project.org")
}

if (!require("patchwork")) {
  install.packages("patchwork", repos = "http://cran.us.r-project.org")
}

if (!require("latex2exp")) {
  install.packages("latex2exp", repos = "http://cran.us.r-project.org")
}

library(tidyverse)
library(broom)
library(patchwork)

kids <- read_csv("https://github.com/febse/data/raw/main/econ/childiq.csv") %>%
  select(kid_score, mom_hs)
```

```{r}
#| label: tbl-kids-head
#| tbl-cap: "First few rows of the data set `kids`."

kids %>%
  head() %>%
  knitr::kable()
```

Variables description:

-   `kid_score`: (numeric) IQ-Wert
-   `mom_hs` (numeric): 1: Mutter hat einen High-School Abschluss, 0: Mutter hat keinen High-School Abschluss

```{r}
#| label: fig-kid-score-plot
#| fig-cap: "IQ-Werte der Kinder nach Bildungsstatus der Mutter."

## Where to get the data
kids %>%
  ggplot(
    aes(
      ## Map the status of the mother to the y-axis.
      ## The factor function converts mom_hs to a factor variable
      ## so that ggplot would not treat mom_hs as a continuous variable.
      y = factor(mom_hs),
      ## Map the kid_score column to the x-axis.
      x = kid_score
  )
  ) +
  geom_point(
    ## Add some noise to each observation so that we can 
    ## see the collection of dots. Without this noise
    ## all dots would lie on two straight lines
    position = "jitter"
  ) +
  ## Draws the two boxplots to help us see the centers and the spreads
  ## of the distributions of the scores in the two groups
  geom_boxplot(
    ## Makes the boxplots transparent so that we can see the dots
    ## behind them
    alpha = 0.5
  ) +
  ## Sets human-readable labels for the two axes
  labs(
    x = "IQ-Wert",
    y = "Bildungsstatus der Mutter"
  )
```

::: {#exr-summary-kids}
Berechnen Sie die durchschnittlichen IQ-Werte der Kinder in den beiden Gruppen. Welche Gruppe hat den höheren IQ-Wert?
```{r}
# Compute the average IQ scores for the two groups
# Uncomment the following code and fill in the ellipsis

# kids %>%
#   group_by(...) %>%
#   summarize(
#     ... = mean(...)
#   )
```
:::

:::{#exr-kids-lm}

$$
\widehat{\text{kid\_score}} = \beta_0 + \beta_1 \cdot \text{mom\_hs}
$$

```{r}
# Schätzen Sie das Modell mit der lm Funktion

```
:::
