# Empfohlene Literatur {.unnumbered}

<https://tinyurl.com/jjdb5vzd>

1. Weisberg ([2014](https://febse.github.io/econ2025/references.html#ref-WEISBERG2014AppliedLinearRegression)) ist ein klassisches Lehrbuch zur linearen Regression.

2.  @JAMES2023IntroductionStatisticalLearning

Das Lehrbuch ist eine Einführung in die statistische Lerntheorie und behandelt das lineare Regressionsmodell, das den Kern des Kurses bildet. Das Lehrbuch enthält Beispielanwendungen in Python. [Sie können das Buch kostenlos herunterladen](https://hastie.su.domains/ISLP/ISLP_website.pdf.download.html).

3.  @MCKINNEY2022PythonDataAnalysis

Das Buch ist eine Einführung in die Datenanalyse mit Python und behandelt die Grundlagen der Programmiersprache und der Datenanalyse.

4.  @GELMAN2021RegressionOtherStories:

Regression and other stories. Cambridge New York, NY Port Melbourne, VIC New Delhi Singapore: Cambridge University Press (Analytical methods for social research). Available at: https://doi.org/10.1017/9781139161879.